on:
  push:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest

    env:
      IMAGE: ghcr.io/${{ github.repository }}
 

    steps:
      - uses: actions/checkout@v2

     
      - name: Build image
        run: docker pull golang #pulling an image

      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publish image
        run: docker tag golang ghcr.io/arya062000/container-registry-sample:latest
        
      - name: Push image
        run: docker push ghcr.io/arya062000/container-registry-sample:latest
